name: Preprocessing CI

on:
  push:
    paths:
      - 'customer_shopping_data_raw/**'
      - 'preprocessing/automate_*.py'
  workflow_dispatch:

jobs:
  preprocess:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.9'
      - run: pip install pandas numpy scikit-learn
      - run: |
          cd preprocessing
          python automate_Idlofi-Zahir-Rajaba.py
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: '🤖 Auto-preprocessing: update dataset'
          file_pattern: '*.csv *.txt'